sweep:
  method: random
  metric:
    name: train_loss
    goal: minimize
  parameters:
    learning_rate:
      values: [1e-4, 3e-4, 5e-4]
    per_device_train_batch_size:
      values: [8, 16]
    num_train_epochs:
      values: [1, 2, 3]
    lora_r:
      values: [64, 128]
    lora_alpha:
      values: [16, 32]
    lora_dropout:
      values: [0.05, 0.1]
